import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { getUserByToken } from "../auth/index.js";
import { PlatformAuthorizationError, PlatformConflictError, PlatformNotFoundError, PlatformPreconditionError } from "../platform/service.js";
import { PROJECT_TYPES, uuidV7 } from "../platform/foundation.js";
import type { PlatformDatabase } from "../platform/postgres.js";
import { PlanningService } from "./service.js";
import type { BlueprintContent, PlanningMode } from "./model.js";

export async function registerPlanningRoutes(app: FastifyInstance, database: PlatformDatabase): Promise<void> {
  if (!app.hasDecorator("planningDatabase")) app.decorate("planningDatabase", database);
  const service = new PlanningService(database);
  app.post("/api/v1/projects/:projectId/project-links", async (request, reply) => run(reply, async () => {
    const user = await auth(request); const workspaceId = await workspace(request, user.id); const body = request.body as { toProjectId?: string; linkType?: "derived-from"|"restores-archive"|"retries"|"repairs" };
    if (!body?.toProjectId || !body.linkType) return problem(reply, 422, "VALIDATION_FAILED", "toProjectId and linkType are required.");
    return service.createProjectLink(context(request,user.id,workspaceId), (request.params as {projectId:string}).projectId, body.toProjectId, body.linkType);
  }));
  app.post("/api/v1/projects/:projectId/transition", async (request, reply) => run(reply, async () => {
    const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as { status?: string }; const expected=parseEtag(header(request,"if-match"));
    if (!body?.status) return problem(reply,422,"VALIDATION_FAILED","status is required.");
    const result=await service.transitionProject(context(request,user.id,workspaceId), (request.params as {projectId:string}).projectId, expected, body.status) as { version: number }; reply.header("ETag",etag(result.version)); return result;
  }));
  app.post("/api/v1/projects/:projectId/workloads", async (request, reply) => run(reply, async () => {
    const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as {name?:string;kind?:string;ownerRef?:string;tags?:string[]};
    if (!body?.name || !body.kind) return problem(reply,422,"VALIDATION_FAILED","name and kind are required.");
    const workload=await service.createWorkload(context(request,user.id,workspaceId), (request.params as {projectId:string}).projectId, { name: body.name, kind: body.kind, ownerRef: body.ownerRef, tags: body.tags }); reply.code(201); return workload;
  }));
  app.get("/api/v1/projects/:projectId/workloads", async (request, reply) => run(reply, async () => { const user=await auth(request); const workspaceId=await workspace(request,user.id); return { items: await service.listWorkloads(workspaceId,(request.params as {projectId:string}).projectId) }; }));
  app.get("/api/v1/workloads/:workloadId", async (request, reply) => run(reply, async () => { const user=await auth(request); return service.getWorkload(await workspace(request,user.id),(request.params as {workloadId:string}).workloadId); }));
  app.post("/api/v1/workloads/:workloadId/placements", async (request, reply) => run(reply, async () => { const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as {projectId?:string;endpointId?:string;archiveRefId?:string;placementType?:"source"|"target"|"active"|"standby"|"archived"|"restored";authorityState?:"none"|"source"|"target"|"committed"|"historical"}; if(!body?.placementType||!body.authorityState)return problem(reply,422,"VALIDATION_FAILED","placementType and authorityState are required."); const result=await service.createPlacement(context(request,user.id,workspaceId),{workloadId:(request.params as {workloadId:string}).workloadId,...body,placementType:body.placementType,authorityState:body.authorityState});reply.code(201);return result;}));
  app.get("/api/v1/workloads/:workloadId/blueprints", async (request, reply) => run(reply, async () => { const user=await auth(request); return { items: await service.listBlueprints(await workspace(request,user.id),(request.params as {workloadId:string}).workloadId) }; }));
  app.post("/api/v1/workloads/:workloadId/blueprints", async (request, reply) => run(reply, async () => {
    const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as {content?:BlueprintContent;origin?:"manual"|"legacy-import"|"update-proposal"}; if (!body?.content) return problem(reply,422,"VALIDATION_FAILED","content is required.");
    const blueprint=await service.createBlueprintDraft(context(request,user.id,workspaceId),(request.params as {workloadId:string}).workloadId,body.content,body.origin); reply.code(201); return blueprint;
  }));
  app.get("/api/v1/blueprint-revisions/:revisionId", async (request, reply) => run(reply, async () => { const user=await auth(request); return service.getBlueprint(await workspace(request,user.id),(request.params as {revisionId:string}).revisionId); }));
  app.post("/api/v1/blueprint-revisions/:revisionId/confirm", async (request, reply) => run(reply, async () => { const user=await auth(request); const workspaceId=await workspace(request,user.id); const result=await service.confirmBlueprint(context(request,user.id,workspaceId),(request.params as {revisionId:string}).revisionId,parseEtag(header(request,"if-match"))); reply.header("ETag",etag(result.version)); return result; }));
  app.post("/api/v1/blueprint-revisions/:revisionId/evaluate-readiness", async (request, reply) => run(reply, async () => { const user=await auth(request); const body=request.body as {mode?:PlanningMode}; if (!body?.mode) return problem(reply,422,"VALIDATION_FAILED","mode is required."); return service.evaluateBlueprintReadiness(context(request,user.id,await workspace(request,user.id)),(request.params as {revisionId:string}).revisionId,body.mode); }));
  app.post("/api/v1/projects/:projectId/decision-set-revisions", async (request, reply) => run(reply, async () => { const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as {content?:Record<string,unknown>}; if (!body?.content) return problem(reply,422,"VALIDATION_FAILED","content is required."); const result=await service.createDecisionSet(context(request,user.id,workspaceId),(request.params as {projectId:string}).projectId,body.content); reply.code(201); return result; }));
  app.get("/api/v1/projects/:projectId/decision-set-revisions", async (request) => { const user=await auth(request); return { items: await service.listDecisionSets(await workspace(request,user.id),(request.params as {projectId:string}).projectId) }; });
  app.get("/api/v1/decision-set-revisions/:revisionId", async (request) => { const user=await auth(request); return service.getDecisionSet(await workspace(request,user.id),(request.params as {revisionId:string}).revisionId); });
  app.post("/api/v1/projects/:projectId/migration-estimates", async (request, reply) => run(reply, async () => { const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as {estimate?:Record<string,unknown>;confidence?:"low"|"medium"|"high";calculatedAt?:string;expiresAt?:string}; if(!body?.estimate||!body.confidence||!body.calculatedAt||!body.expiresAt)return problem(reply,422,"VALIDATION_FAILED","estimate, confidence, calculatedAt and expiresAt are required.");const result=await service.createMigrationEstimate(context(request,user.id,workspaceId),{projectId:(request.params as {projectId:string}).projectId,estimate:body.estimate,confidence:body.confidence,calculatedAt:body.calculatedAt,expiresAt:body.expiresAt});reply.code(201);return result;}));
  app.post("/api/v1/projects/:projectId/plan-compilations", async (request, reply) => run(reply, async () => {
    const user=await auth(request); const workspaceId=await workspace(request,user.id); const body=request.body as {mode?:PlanningMode;blueprintRevisionIds?:string[];decisionSetRevisionId?:string;sourceSnapshot?:{id:string;hash:string};targetSnapshot?:{id:string;hash:string};archiveVersion?:{id:string;hash:string};capability?:{id:string;hash:string;version:string;certifiedModes:PlanningMode[]};policy?:{id:string;hash:string;version:string};estimate?:Record<string,unknown>};
    if (!body?.mode || !body.blueprintRevisionIds?.length || !body.decisionSetRevisionId) return problem(reply,422,"VALIDATION_FAILED","mode, blueprintRevisionIds and decisionSetRevisionId are required.");
    const operationId=await service.requestCompilation(context(request,user.id,workspaceId),{projectId:(request.params as {projectId:string}).projectId,mode:body.mode,blueprintRevisionIds:body.blueprintRevisionIds,decisionSetRevisionId:body.decisionSetRevisionId,sourceSnapshot:body.sourceSnapshot,targetSnapshot:body.targetSnapshot,archiveVersion:body.archiveVersion,capability:body.capability ?? {id:"built-in-contract",hash:"0".repeat(64),version:"1.0.0",certifiedModes:["build"]},policy:body.policy ?? {id:"default-policy",hash:"0".repeat(64),version:"1.0.0"},estimate:body.estimate});
    reply.code(202).header("Location",`/api/v1/plan-compilations/${operationId}`); return service.getCompilation(workspaceId,operationId);
  }));
  app.get("/api/v1/plan-compilations/:compilationId", async (request) => { const user=await auth(request); return service.getCompilation(await workspace(request,user.id),(request.params as {compilationId:string}).compilationId); });
  app.get("/api/v1/projects/:projectId/plans", async (request) => { const user=await auth(request); return {items:await service.listPlans(await workspace(request,user.id),(request.params as {projectId:string}).projectId)}; });
  app.get("/api/v1/plans/:planRevisionId", async (request) => { const user=await auth(request); return service.getPlan(await workspace(request,user.id),(request.params as {planRevisionId:string}).planRevisionId); });
  app.post("/api/v1/plans/:planRevisionId/submit-for-approval", async (request, reply) => run(reply, async () => { const user=await auth(request); const result=await service.submitForApproval(context(request,user.id,await workspace(request,user.id)),(request.params as {planRevisionId:string}).planRevisionId,parseEtag(header(request,"if-match"))); reply.code(201); return result; }));
  app.post("/api/v1/plan-approvals/:approvalId/approve", async (request, reply) => run(reply, async () => { const user=await auth(request); if(user.role!=="admin") return problem(reply,403,"FORBIDDEN","Plan approval permission is required."); const body=request.body as {reason?:string;acceptedRiskIds?:string[]}; const result=await service.decideApproval(context(request,user.id,await workspace(request,user.id)),(request.params as {approvalId:string}).approvalId,parseEtag(header(request,"if-match")),"approved",body?.reason ?? "",body?.acceptedRiskIds ?? []); return result; }));
  for (const decision of ["reject","revoke"] as const) app.post(`/api/v1/plan-approvals/:approvalId/${decision}`, async (request) => { const user=await auth(request); const body=request.body as {reason?:string;acceptedRiskIds?:string[]}; return service.decideApproval(context(request,user.id,await workspace(request,user.id)),(request.params as {approvalId:string}).approvalId,parseEtag(header(request,"if-match")),decision === "reject" ? "rejected" : "revoked",body?.reason ?? "",body?.acceptedRiskIds ?? []); });
  app.post("/api/v1/plans/:planRevisionId/runs", async (request, reply) => run(reply, async()=>{
    const execution=(request.server as FastifyInstance & {executionService?:import("../execution/service.js").ExecutionService}).executionService;
    if(!execution)return problem(reply,404,"RUN_NOT_AVAILABLE","Durable Execution is locked until Phase 2.");
    const user=await auth(request);const workspaceId=await workspace(request,user.id);const body=request.body as Record<string,unknown>??{};const planId=(request.params as {planRevisionId:string}).planRevisionId;
    const plan=(await execution.database.pool.query<{project_id:string}>("SELECT project_id FROM planning.plan_revisions WHERE workspace_id=$1 AND id=$2",[workspaceId,planId])).rows[0];if(!plan)return problem(reply,404,"NOT_FOUND","Resource not found.");
    const result=await execution.createRun(context(request,user.id,workspaceId),{projectId:plan.project_id,planRevisionId:planId,expectedPlanHash:String(body.expectedPlanHash??body.planHash??""),approvalId:String(body.approvalId??""),expectedApprovalHash:String(body.expectedApprovalHash??""),runType:(body.runType as "build")??"build",operationClass:(body.operationClass as "live")??"live",priority:Number(body.priority??0)});
    reply.code(202).header("Location",`/api/v1/runs/${result.id}`).header("ETag",`"${result.version}"`);return result;
  }));
}

async function auth(request: FastifyRequest) { const token=header(request,"authorization")?.replace(/^Bearer\s+/i,""); const user=await getUserByToken(token); if(!user) throw Object.assign(new Error("Authentication required."),{statusCode:401,code:"AUTHENTICATION_REQUIRED"}); return user; }
async function workspace(request:FastifyRequest,actorId:string){ const value=header(request,"x-workspace-id"); if(!value) throw new PlatformAuthorizationError("Workspace context is required."); const result=await (request.server as FastifyInstance & {planningDatabase?:PlatformDatabase}).planningDatabase?.pool.query("SELECT 1 FROM core.workspace_memberships WHERE actor_id=$1 AND workspace_id=$2",[actorId,value]); if(!result?.rowCount) throw new PlatformAuthorizationError("Workspace access denied."); return value; }
function context(request:FastifyRequest,actorId:string,workspaceId:string){const idempotencyKey=header(request,"idempotency-key");if(!idempotencyKey)throw Object.assign(new Error("Idempotency-Key header is required."),{statusCode:422,code:"VALIDATION_FAILED"});return{actorId,workspaceId,requestId:request.id,correlationId:header(request,"x-correlation-id")??uuidV7(),idempotencyKey};}
async function run(reply:FastifyReply, fn:()=>Promise<unknown>){try{return await fn();}catch(error){if(error instanceof PlatformConflictError)return problem(reply,409,"CONFLICT",error.message);if(error instanceof PlatformPreconditionError)return problem(reply,412,"PRECONDITION_FAILED",error.message);if(error instanceof PlatformNotFoundError)return problem(reply,404,"NOT_FOUND","Resource not found.");if(error instanceof PlatformAuthorizationError)return problem(reply,404,"NOT_FOUND","Resource not found.");const e=error as {statusCode?:number;code?:string;message?:string};return problem(reply,e.statusCode??422,e.code??"VALIDATION_FAILED",e.message??"Request failed.");}}
function header(request:FastifyRequest,name:string){const value=request.headers[name];return Array.isArray(value)?value[0]:value;}
function parseEtag(value:string|undefined){if(!value)throw Object.assign(new Error("If-Match header is required."),{statusCode:422,code:"VALIDATION_FAILED"});const match=/^\"?(\d+)\"?$/.exec(value.trim());if(!match)throw Object.assign(new Error("If-Match must contain a numeric version."),{statusCode:422,code:"VALIDATION_FAILED"});return Number(match[1]);}
function etag(version:number){return`\"${version}\"`;}
function problem(reply:FastifyReply,status:number,code:string,detail:string){reply.code(status).type("application/problem+json");return{type:"about:blank",title:"Planning request failed",status,code,detail};}
