import { useState } from "react";
import { useTranslation } from "react-i18next";
import { ClipboardCheck, FileLock2, RefreshCw } from "lucide-react";
import { confirmPhase1Blueprint, createPhase1Blueprint, createPhase1Compilation, createPhase1Decision, createPhase1Project, createPhase1Workload, getPhase1Compilation, getPhase1Plan, listPhase1Projects, listPhase1Workloads, type Phase1Compilation, type Phase1Plan, type Phase1Project, type Phase1Workload } from "../api";
import { Button } from "./ui/Button";
import { Card } from "./ui/Card";
import { Badge } from "./ui/Badge";

export function Phase1PlanningPanel({ authToken }: { authToken: string }) {
  const { t } = useTranslation();
  const [projects,setProjects]=useState<Phase1Project[]>([]); const [project,setProject]=useState<Phase1Project>(); const [workloads,setWorkloads]=useState<Phase1Workload[]>([]); const [compilation,setCompilation]=useState<Phase1Compilation>(); const [plan,setPlan]=useState<Phase1Plan>(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function refreshProjects(){setError("");try{const items=await listPhase1Projects(authToken);setProjects(items);if(!project&&items[0])await selectProject(items[0]);}catch(reason){setError(message(reason));}}
  async function selectProject(next:Phase1Project){setProject(next);setPlan(undefined);setCompilation(undefined);setWorkloads(await listPhase1Workloads(authToken,next.workspaceId,next.id));}
  async function createWorkspace(){setBusy(true);setError("");try{const next=await createPhase1Project(authToken,{type:"build",name:t("phase1Planning.defaultProject")});setProjects((items)=>[next,...items]);await selectProject(next);}catch(reason){setError(message(reason));}finally{setBusy(false);}}
  async function createPlanningFixture(){if(!project)return;setBusy(true);setError("");try{const workload=await createPhase1Workload(authToken,project.workspaceId,project.id,{name:t("phase1Planning.defaultWorkload"),kind:"web-app"});setWorkloads((items)=>[...items,workload]);const draft=await createPhase1Blueprint(authToken,project.workspaceId,workload.id,blueprintFixture(t("phase1Planning.defaultWorkload")));const confirmed=await confirmPhase1Blueprint(authToken,project.workspaceId,draft.id,draft.version);const decision=await createPhase1Decision(authToken,project.workspaceId,project.id,{});setCompilation(await createPhase1Compilation(authToken,project.workspaceId,project.id,{mode:"build",blueprintRevisionIds:[confirmed.id],decisionSetRevisionId:decision.id,targetSnapshot:{id:"planning-preview-target",hash:"a".repeat(64)}}));}catch(reason){setError(message(reason));}finally{setBusy(false);}}
  async function refreshCompilation(){if(!project||!compilation)return;setBusy(true);try{const next=await getPhase1Compilation(authToken,project.workspaceId,compilation.id);setCompilation(next);if(next.resultPlanRevisionId)setPlan(await getPhase1Plan(authToken,project.workspaceId,next.resultPlanRevisionId));}catch(reason){setError(message(reason));}finally{setBusy(false);}}
  return <section className="phase1-planning" aria-labelledby="phase1-planning-title">
    <header className="phase1-planning-header"><div><h2 id="phase1-planning-title"><FileLock2 size={18}/>{t("phase1Planning.title")}</h2><p>{t("phase1Planning.boundary")}</p></div><div className="phase1-planning-actions"><Button variant="secondary" onClick={()=>void refreshProjects()} loading={busy} icon={<RefreshCw size={15}/>}>{t("phase1Planning.refreshProjects")}</Button><Button variant="primary" onClick={()=>void createWorkspace()} loading={busy}>{t("phase1Planning.newProject")}</Button></div></header>
    {error?<div className="filter-status" role="alert">{error}</div>:null}
    <div className="phase1-planning-layout"><div className="phase1-project-list" role="list">{projects.map((item)=><button type="button" key={item.id} className={item.id===project?.id?"active":""} onClick={()=>void selectProject(item)}><strong>{item.name}</strong><span>{item.type} · {item.status}</span></button>)}</div>
      <Card as="article"><div className="phase1-planning-toolbar"><div><strong>{project?.name??t("phase1Planning.selectProject")}</strong>{project?<small>{t("phase1Planning.workspaceCount",{count:workloads.length})}</small>:null}</div>{project?<Button variant="secondary" onClick={()=>void createPlanningFixture()} loading={busy} icon={<ClipboardCheck size={16}/>}>{t("phase1Planning.createContract")}</Button>:null}</div>
        {compilation?<div className="phase1-compilation"><div><Badge tone={compilation.state==="succeeded"?"ok":"warn"}>{compilation.state}</Badge><code>{compilation.id}</code></div><Button variant="ghost" onClick={()=>void refreshCompilation()} disabled={busy} icon={<RefreshCw size={15}/>}>{t("phase1Planning.refresh")}</Button></div>:<p className="filter-status">{t("phase1Planning.empty")}</p>}
        {plan?<div className="phase1-plan-contract"><div><strong>{t("phase1Planning.planHash")}</strong><code>{plan.planHash}</code></div><dl><div><dt>{t("phase1Planning.stages")}</dt><dd>{plan.canonicalContent.stages.length}</dd></div><div><dt>{t("phase1Planning.actions")}</dt><dd>{plan.canonicalContent.actions.length}</dd></div><div><dt>{t("phase1Planning.contracts")}</dt><dd>{plan.canonicalContent.contracts.length}</dd></div><div><dt>{t("phase1Planning.risks")}</dt><dd>{plan.canonicalContent.risks.length}</dd></div></dl><p>{t("phase1Planning.noExecution")}</p></div>:null}
      </Card></div>
  </section>;
}

function message(reason:unknown){return reason instanceof Error?reason.message:String(reason);}
function blueprintFixture(name:string){return{identity:{name,kind:"web-app",provenance:{source:"manual"},scope:{}},components:[{key:"app",kind:"service"}],runtime:{executionModel:"systemd",entrypoint:"artifact-entrypoint-ref",workingDirectory:"/srv/app",runUser:"app",runGroup:"app",environmentRefs:[],environmentFileRefs:["secret-requirement:app-env"],enabled:true,desiredState:"active",restartPolicy:"on-failure",restartDelaySeconds:5,after:["network-online.target"],before:[],wants:["network-online.target"],requires:[],startupTimeoutSeconds:60,shutdownTimeoutSeconds:30,resourceLimits:{},securityContext:{noNewPrivileges:true},socketActivation:false,timerActivation:false,healthCheck:{kind:"http",path:"/health"},allowedWritePaths:["/srv/app/uploads"],stateDirectories:["app"],runtimeDirectories:["app"]},deployment:{sourceType:"git",reference:"https://example.invalid/repository.git",exactVersion:"review-required",checksum:"a".repeat(64),lockfile:"package-lock.json",provenance:{kind:"manual"},fallbackStrategy:"blocked"},config:[],datasets:[],secretRequirements:[{id:"app-env",purpose:"application environment",providerBindingRef:"provider-ref:app-env",required:true}],endpoints:[{kind:"http",port:8080}],systemIdentities:[{user:"app",group:"app"}],scheduledTasks:[],dependencies:[],externalDependencies:[],ephemeralState:{httpRequests:"drain",databaseTransactions:"quiesce",fileLocks:"restart",activeWriters:"quiesce",inMemorySessions:"discard-with-warning",activeJobs:"requeue",leaderElection:"restart",scheduledExecutions:"requeue",unpersistedMessages:"requeue"},compatibility:{architectures:["x64"]},verification:[{kind:"http",path:"/health"}],operationalRequirements:{},migrationRequirements:{},captureRequirements:{},knownLimitations:["Planning contract only; no action execution is available."]};}
