import { canonicalHash, redact, uuidV7 } from "../platform/foundation.js";
import { PlatformDatabase } from "../platform/postgres.js";
import { PlatformConflictError, PlatformNotFoundError, PlatformPreconditionError } from "../platform/service.js";
import { assertExecutionSafe, assertRunTransition, checkpointHash, type AdapterAction, type ExecutionAdapter, type RunState } from "./model.js";

export interface ExecutionContext { actorId:string; workspaceId:string; requestId:string; idempotencyKey:string }
export interface RunCreateInput { projectId:string; planRevisionId:string; expectedPlanHash:string; approvalId:string; expectedApprovalHash:string; runType:"build"|"migration"|"capture"|"restore"|"verification"|"rollback"; operationClass?:"live"|"dry-run"|"rehearsal"|"verification"|"rollback"; parentRunId?:string; rollbackOfRunId?:string; priority?:number; bindingHashes?:Array<{type:string;key:string;hash:string}> }

export class ExecutionService {
  constructor(readonly database:PlatformDatabase) {}

  async createRun(ctx:ExecutionContext,input:RunCreateInput):Promise<Record<string,unknown>> {
    const requestHash=canonicalHash(input);
    return this.database.transaction(async client=>{
      const prior=await client.query<Record<string,unknown>>(`SELECT * FROM execution.execution_runs WHERE workspace_id=$1 AND requested_by=$2 AND idempotency_key=$3`,[ctx.workspaceId,ctx.actorId,ctx.idempotencyKey]);
      if(prior.rowCount){if(prior.rows[0].request_hash!==requestHash)throw new PlatformConflictError("Idempotency key was already used with a different Run request.");return this.toRun(prior.rows[0]);}
      const plan=(await client.query<Record<string,unknown>>(`SELECT * FROM planning.plan_revisions WHERE workspace_id=$1 AND id=$2 FOR SHARE`,[ctx.workspaceId,input.planRevisionId])).rows[0];
      const approval=(await client.query<Record<string,unknown>>(`SELECT * FROM planning.plan_approvals WHERE workspace_id=$1 AND id=$2 FOR SHARE`,[ctx.workspaceId,input.approvalId])).rows[0];
      if(!plan||!approval)throw new PlatformNotFoundError("Plan or Approval not found.");
      if(plan.status!=="approved"||approval.status!=="approved")throw new PlatformPreconditionError("Plan approval is not active.");
      if(plan.plan_hash!==input.expectedPlanHash||approval.approved_plan_hash!==input.expectedPlanHash||approval.approval_hash!==input.expectedApprovalHash)throw new PlatformPreconditionError("Exact Plan/Approval hash binding failed.");
      if(approval.expires_at && new Date(String(approval.expires_at)).getTime()<=Date.now())throw new PlatformPreconditionError("Approval has expired.");
      const bindings=await client.query<Record<string,unknown>>(`SELECT binding_type,binding_key,resource_hash,metadata FROM planning.plan_input_bindings WHERE workspace_id=$1 AND plan_revision_id=$2 ORDER BY binding_type,binding_key`,[ctx.workspaceId,input.planRevisionId]);
      const bindingHash=canonicalHash(bindings.rows.map(row=>({type:row.binding_type,key:row.binding_key,hash:row.resource_hash})));
      if(input.bindingHashes && canonicalHash(input.bindingHashes.map(x=>({type:x.type,key:x.key,hash:x.hash})).sort((a,b)=>`${a.type}:${a.key}`.localeCompare(`${b.type}:${b.key}`)))!==bindingHash)throw new PlatformPreconditionError("Material input drift requires a new PlanRevision.");
      const id=uuidV7(); const runType=input.runType; const operationClass=input.operationClass??"live";
      const inserted=await client.query<Record<string,unknown>>(`INSERT INTO execution.execution_runs(id,workspace_id,project_id,run_type,operation_class,plan_revision_id,plan_hash,approval_id,approval_hash,binding_hash,parent_run_id,rollback_of_run_id,state,requested_by,idempotency_key,request_hash)
        VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'queued',$13,$14,$15) RETURNING *`,[id,ctx.workspaceId,input.projectId,runType,operationClass,input.planRevisionId,input.expectedPlanHash,input.approvalId,input.expectedApprovalHash,bindingHash,input.parentRunId??null,input.rollbackOfRunId??null,ctx.actorId,ctx.idempotencyKey,requestHash]);
      await client.query(`INSERT INTO execution.run_input_bindings(workspace_id,run_id,binding_type,binding_key,resource_hash,metadata) SELECT workspace_id,$2,binding_type,binding_key,resource_hash,metadata FROM planning.plan_input_bindings WHERE workspace_id=$1 AND plan_revision_id=$3`,[ctx.workspaceId,id,input.planRevisionId]);
      const stages=await client.query<Record<string,unknown>>(`SELECT id,stage_key,sequence,required FROM planning.plan_stages WHERE workspace_id=$1 AND plan_revision_id=$2 ORDER BY sequence`,[ctx.workspaceId,input.planRevisionId]);
      for(const stage of stages.rows)await client.query(`INSERT INTO execution.stage_runs(id,workspace_id,run_id,stage_key,state,sequence) VALUES($1,$2,$3,$4,'pending',$5)`,[uuidV7(),ctx.workspaceId,id,stage.stage_key,stage.sequence]);
      const actions=await client.query<Record<string,unknown>>(`SELECT id,stage_id,action_key FROM planning.plan_actions WHERE workspace_id=$1 AND plan_revision_id=$2 ORDER BY action_key`,[ctx.workspaceId,input.planRevisionId]);
      for(const action of actions.rows){const stage=(await client.query<{id:string}>(`SELECT id FROM execution.stage_runs WHERE run_id=$1 AND stage_key=(SELECT stage_key FROM planning.plan_stages WHERE id=$2)`,[id,action.stage_id])).rows[0];await client.query(`INSERT INTO execution.action_runs(id,workspace_id,run_id,stage_run_id,plan_action_id,action_key,state) VALUES($1,$2,$3,$4,$5,$6,'pending')`,[uuidV7(),ctx.workspaceId,id,stage.id,action.id,action.action_key]);}
      await client.query(`INSERT INTO execution.queue_items(id,workspace_id,run_id,state,priority) VALUES($1,$2,$3,'queued',$4)`,[uuidV7(),ctx.workspaceId,id,input.priority??0]);
      await this.event(client,ctx.workspaceId,id,"run.created",{runId:id,planHash:input.expectedPlanHash});
      return this.toRun(inserted.rows[0]);
    });
  }

  async getRun(workspaceId:string,runId:string):Promise<Record<string,unknown>>{const row=(await this.database.pool.query<Record<string,unknown>>("SELECT * FROM execution.execution_runs WHERE workspace_id=$1 AND id=$2",[workspaceId,runId])).rows[0];if(!row)throw new PlatformNotFoundError("Run not found.");return this.toRun(row);}
  async listRuns(workspaceId:string,projectId?:string):Promise<Record<string,unknown>[]> {const rows=await this.database.pool.query<Record<string,unknown>>(`SELECT * FROM execution.execution_runs WHERE workspace_id=$1 ${projectId?"AND project_id=$2":""} ORDER BY created_at DESC`,projectId?[workspaceId,projectId]:[workspaceId]);return rows.rows.map(row=>this.toRun(row));}
  async children(workspaceId:string,runId:string,kind:"stages"|"actions"|"events"):Promise<Record<string,unknown>[]> {const q=kind==="stages"?"SELECT * FROM execution.stage_runs WHERE workspace_id=$1 AND run_id=$2 ORDER BY sequence":kind==="actions"?"SELECT * FROM execution.action_runs WHERE workspace_id=$1 AND run_id=$2 ORDER BY action_key":"SELECT * FROM execution.run_events WHERE workspace_id=$1 AND run_id=$2 ORDER BY sequence";return (await this.database.pool.query(q,[workspaceId,runId])).rows;}

  async requestControl(ctx:ExecutionContext,runId:string,command:"pause"|"resume"|"cancel",expectedVersion:number,reason:string):Promise<Record<string,unknown>> {return this.database.transaction(async client=>{const row=(await client.query<Record<string,unknown>>("SELECT * FROM execution.execution_runs WHERE workspace_id=$1 AND id=$2 FOR UPDATE",[ctx.workspaceId,runId])).rows[0];if(!row)throw new PlatformNotFoundError("Run not found.");if(Number(row.version)!==expectedVersion)throw new PlatformPreconditionError("Run version is stale.");const target=command==="pause"?"pause-requested":command==="cancel"?"cancel-requested":"queued";assertRunTransition(String(row.state) as RunState,target);await client.query(`INSERT INTO execution.run_control_requests(id,workspace_id,run_id,command,state,reason,requested_by) VALUES($1,$2,$3,$4,'pending',$5,$6)`,[uuidV7(),ctx.workspaceId,runId,command,reason,ctx.actorId]);const updated=(await client.query<Record<string,unknown>>("UPDATE execution.execution_runs SET state=$3,version=version+1,updated_at=now() WHERE workspace_id=$1 AND id=$2 RETURNING *",[ctx.workspaceId,runId,target])).rows[0];await this.event(client,ctx.workspaceId,runId,`run.${command}.requested`,{reason,requestedBy:ctx.actorId});return this.toRun(updated);});}

  async claimNext(workerId:string,workerVersion="phase2-v1"):Promise<{runId:string;token:string;generation:number}|undefined>{return this.database.transaction(async client=>{const session=(await client.query<{id:string}>(`INSERT INTO execution.worker_sessions(id,worker_id,version,state) VALUES($1,$2,$3,'active') ON CONFLICT(worker_id,id) DO UPDATE SET heartbeat_at=now() RETURNING id`,[uuidV7(),workerId,workerVersion])).rows[0];const queue=(await client.query<Record<string,unknown>>(`SELECT * FROM execution.queue_items WHERE (state='queued' AND available_at<=now()) OR (state='claimed' AND lease_expires_at<now()) ORDER BY priority DESC,created_at FOR UPDATE SKIP LOCKED LIMIT 1`)).rows[0];if(!queue)return undefined;const token=uuidV7();const generation=Number(queue.lease_generation)+1;await client.query(`UPDATE execution.queue_items SET state='claimed',claimed_by=$2,claim_token=$3,lease_generation=$4,lease_expires_at=now()+interval '30 seconds',attempt_count=attempt_count+1,updated_at=now() WHERE id=$1`,[queue.id,workerId,token,generation]);await client.query(`INSERT INTO execution.worker_leases(workspace_id,run_id,worker_session_id,claim_token,generation,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval '30 seconds') ON CONFLICT(run_id) DO UPDATE SET worker_session_id=excluded.worker_session_id,claim_token=excluded.claim_token,generation=excluded.generation,heartbeat_at=now(),expires_at=excluded.expires_at`,[queue.workspace_id,queue.run_id,session.id,token,generation]);await client.query(`UPDATE execution.execution_runs SET state='claimed',fencing_token=$3,version=version+1,started_at=coalesce(started_at,now()) WHERE workspace_id=$1 AND id=$2 AND state IN ('queued','recovering','claimed','running')`,[queue.workspace_id,queue.run_id,generation]);return{runId:String(queue.run_id),token,generation};});}

  async heartbeat(workerId:string,runId:string,token:string):Promise<void>{const result=await this.database.pool.query(`UPDATE execution.worker_leases l SET heartbeat_at=now(),expires_at=now()+interval '30 seconds' FROM execution.worker_sessions s WHERE l.worker_session_id=s.id AND s.worker_id=$1 AND l.run_id=$2 AND l.claim_token=$3 AND l.expires_at>now()`,[workerId,runId,token]);if(!result.rowCount)throw new PlatformPreconditionError("Worker lease lost.");}

  async executeClaimed(claim:{runId:string;token:string;generation:number},adapter:ExecutionAdapter):Promise<Record<string,unknown>> {const run=(await this.database.pool.query<Record<string,unknown>>("SELECT * FROM execution.execution_runs WHERE id=$1",[claim.runId])).rows[0];if(!run)throw new PlatformNotFoundError("Run not found.");await this.fencedRun(claim,"running");while(true){const action=await this.nextAction(claim.runId);if(!action)break;const attemptId=uuidV7();const input=action.inputs as Record<string,unknown>;const adapterAction:AdapterAction={id:String(action.plan_action_id),key:String(action.action_key),type:String(action.action_type),inputs:input,resourceKeys:(action.resource_keys as string[]??[]),verificationCheckIds:(action.verification_check_ids as string[]??[]),retryPolicy:(action.retry_policy as {maxAttempts?:number}??{}) ,rollbackDefinition:action.rollback_definition as Record<string,unknown>|undefined};if(!adapter.supports(adapterAction))return this.failAction(claim,action,attemptId,"non-retryable","Unsupported action adapter");for(const key of adapterAction.resourceKeys)await this.acquireResource(String(run.workspace_id),claim.runId,String(action.id),key,claim.generation);await this.startAttempt(claim,action,attemptId);const result=await adapter.execute(adapterAction,{runId:claim.runId,actionRunId:String(action.id),attemptId,idempotencyKey:`${claim.runId}:${action.action_key}`,fencingToken:claim.generation});if(result.outcome==="outcome-unknown"){await this.markUnknown(claim,action,attemptId,result);return this.getRun(String(run.workspace_id),claim.runId);}await this.finishAttempt(claim,action,attemptId,result);await this.releaseResources(String(run.workspace_id),claim.runId,String(action.id));if(result.outcome!=="succeeded")return this.getRun(String(run.workspace_id),claim.runId);}await this.commitIfReady(claim);return this.getRun(String(run.workspace_id),claim.runId);}

  async reconcileUnknown(workspaceId:string,runId:string,actionRunId:string,adapter:ExecutionAdapter):Promise<Record<string,unknown>>{const attempt=(await this.database.pool.query<Record<string,unknown>>("SELECT * FROM execution.action_attempts WHERE workspace_id=$1 AND action_run_id=$2 AND state='outcome-unknown' ORDER BY attempt_number DESC LIMIT 1",[workspaceId,actionRunId])).rows[0];if(!attempt)throw new PlatformNotFoundError("Unknown attempt not found.");const action=(await this.database.pool.query<Record<string,unknown>>(`SELECT a.*,p.action_type,p.inputs,p.resource_keys,p.verification_check_ids,p.retry_policy,p.rollback_definition FROM execution.action_runs a JOIN planning.plan_actions p ON p.id=a.plan_action_id WHERE a.workspace_id=$1 AND a.id=$2`,[workspaceId,actionRunId])).rows[0];const adapterAction:AdapterAction={id:String(action.plan_action_id),key:String(action.action_key),type:String(action.action_type),inputs:(action.inputs??{}) as Record<string,unknown>,resourceKeys:Array.isArray(action.resource_keys)?action.resource_keys as string[]:[],verificationCheckIds:Array.isArray(action.verification_check_ids)?action.verification_check_ids as string[]:[],retryPolicy:(action.retry_policy??{}) as {maxAttempts?:number},rollbackDefinition:action.rollback_definition as Record<string,unknown>|undefined};const result=await adapter.reconcile(adapterAction,{runId,actionRunId,attemptId:String(attempt.id),idempotencyKey:`${runId}:${action.action_key}`,fencingToken:Number(attempt.fencing_token)},(attempt.execution_receipt??{}) as Record<string,unknown>);await this.database.transaction(async client=>{await client.query(`INSERT INTO execution.reconciliation_records(id,workspace_id,run_id,action_run_id,attempt_id,outcome,evidence,evidence_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[uuidV7(),workspaceId,runId,actionRunId,attempt.id,result.outcome,result.evidence,canonicalHash(result.evidence)]);const next=result.outcome==="effect-present-valid"?"succeeded":result.outcome==="effect-absent"?"failed":"blocked";await client.query(`UPDATE execution.action_attempts SET state=$3,completed_at=now() WHERE id=$1 AND workspace_id=$2`,[attempt.id,workspaceId,next==="succeeded"?"succeeded":"failed"]);await client.query(`UPDATE execution.action_runs SET state=$3,version=version+1,completed_at=now() WHERE workspace_id=$1 AND id=$2`,[workspaceId,actionRunId,next]);});return this.getRun(workspaceId,runId);}
  async createRollbackRun(ctx:ExecutionContext,originalRunId:string):Promise<Record<string,unknown>>{const original=(await this.database.pool.query<Record<string,unknown>>("SELECT * FROM execution.execution_runs WHERE workspace_id=$1 AND id=$2",[ctx.workspaceId,originalRunId])).rows[0];if(!original)throw new PlatformNotFoundError("Original Run not found.");return this.createRun(ctx,{projectId:String(original.project_id),planRevisionId:String(original.plan_revision_id),expectedPlanHash:String(original.plan_hash),approvalId:String(original.approval_id),expectedApprovalHash:String(original.approval_hash),runType:"rollback",operationClass:"rollback",parentRunId:originalRunId,rollbackOfRunId:originalRunId});}

  async acquireResource(workspaceId:string,runId:string,actionRunId:string,resourceKey:string,generation:number,ttlSeconds=60):Promise<string>{return this.database.transaction(async client=>{await client.query(`INSERT INTO execution.resource_lock_heads(workspace_id,resource_key) VALUES($1,$2) ON CONFLICT DO NOTHING`,[workspaceId,resourceKey]);await client.query(`SELECT 1 FROM execution.resource_lock_heads WHERE workspace_id=$1 AND resource_key=$2 FOR UPDATE`,[workspaceId,resourceKey]);const conflict=await client.query(`SELECT 1 FROM execution.resource_leases WHERE workspace_id=$1 AND resource_key=$2 AND expires_at>now() AND mode IN ('write','exclusive')`,[workspaceId,resourceKey]);if(conflict.rowCount)throw new PlatformConflictError(`Resource is busy: ${resourceKey}`);const id=uuidV7();await client.query(`INSERT INTO execution.resource_leases(id,workspace_id,resource_key,run_id,action_run_id,mode,fencing_token,expires_at) VALUES($1,$2,$3,$4,$5,'exclusive',$6,now()+($7::text||' seconds')::interval)`,[id,workspaceId,resourceKey,runId,actionRunId,generation,ttlSeconds]);return id;});}
  async releaseResources(workspaceId:string,runId:string,actionRunId:string):Promise<void>{await this.database.pool.query("DELETE FROM execution.resource_leases WHERE workspace_id=$1 AND run_id=$2 AND action_run_id=$3",[workspaceId,runId,actionRunId]);}

  async scheduleOperation(ctx:ExecutionContext,input:{projectId:string;operationType:string;bindingHash:string;deduplicationKey:string;notBefore:Date;runId?:string}):Promise<Record<string,unknown>>{assertExecutionSafe(input);const result=await this.database.pool.query<Record<string,unknown>>(`INSERT INTO execution.scheduled_operations(id,workspace_id,project_id,run_id,operation_type,binding_hash,deduplication_key,not_before,state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'scheduled') ON CONFLICT(workspace_id,deduplication_key) DO UPDATE SET updated_at=now() RETURNING *`,[uuidV7(),ctx.workspaceId,input.projectId,input.runId??null,input.operationType,input.bindingHash,input.deduplicationKey,input.notBefore]);return result.rows[0];}
  async cancelScheduled(workspaceId:string,deduplicationKey:string,reason:string):Promise<void>{await this.database.pool.query("UPDATE execution.scheduled_operations SET state='cancelled',cancel_reason=$3,updated_at=now() WHERE workspace_id=$1 AND deduplication_key=$2 AND state IN ('scheduled','missed')",[workspaceId,deduplicationKey,reason]);}

  private async nextAction(runId:string):Promise<Record<string,unknown>|undefined>{const result=await this.database.pool.query<Record<string,unknown>>(`SELECT a.*,p.action_type,p.inputs,p.resource_keys,p.verification_check_ids,p.retry_policy,p.rollback_definition FROM execution.action_runs a JOIN planning.plan_actions p ON p.id=a.plan_action_id WHERE a.run_id=$1 AND a.state IN ('pending','ready') AND NOT EXISTS (SELECT 1 FROM planning.plan_action_dependencies d JOIN execution.action_runs dep ON dep.plan_action_id=d.from_action_id AND dep.run_id=a.run_id WHERE d.to_action_id=a.plan_action_id AND dep.state NOT IN ('succeeded','skipped')) ORDER BY a.action_key LIMIT 1`,[runId]);return result.rows[0];}
  private async startAttempt(claim:{runId:string;token:string;generation:number},action:Record<string,unknown>,attemptId:string):Promise<void>{await this.database.transaction(async client=>{const fence=await client.query(`SELECT 1 FROM execution.worker_leases WHERE run_id=$1 AND claim_token=$2 AND generation=$3 AND expires_at>now() FOR UPDATE`,[claim.runId,claim.token,claim.generation]);if(!fence.rowCount)throw new PlatformPreconditionError("Worker lease lost.");await client.query(`INSERT INTO execution.action_attempts(id,workspace_id,run_id,action_run_id,attempt_number,worker_id,fencing_token,state,idempotency_key) SELECT $1,r.workspace_id,r.id,$2,a.attempt_count+1,'phase2-worker',$3,'running',$4 FROM execution.execution_runs r JOIN execution.action_runs a ON a.run_id=r.id WHERE r.id=$5 AND a.id=$2`,[attemptId,action.id,claim.generation,`${claim.runId}:${action.action_key}`,claim.runId]);await client.query(`UPDATE execution.action_runs SET state='running',attempt_count=attempt_count+1,current_attempt_id=$2,version=version+1,started_at=coalesce(started_at,now()) WHERE id=$1`,[action.id,attemptId]);});}
  private async finishAttempt(claim:{runId:string;token:string;generation:number},action:Record<string,unknown>,attemptId:string,result:{outcome:string;receipt:Record<string,unknown>;checkpoint?:Record<string,unknown>;errorClass?:string}):Promise<void>{await this.database.transaction(async client=>{const fence=await client.query(`SELECT 1 FROM execution.worker_leases WHERE run_id=$1 AND claim_token=$2 AND generation=$3 AND expires_at>now()`,[claim.runId,claim.token,claim.generation]);if(!fence.rowCount)throw new PlatformPreconditionError("Worker lease lost.");const state=result.outcome==="succeeded"?"succeeded":"failed";await client.query(`UPDATE execution.action_attempts SET state=$2,execution_receipt=$3,error_class=$4,completed_at=now() WHERE id=$1 AND state='running'`,[attemptId,state,result.receipt,result.errorClass??null]);await client.query(`UPDATE execution.action_runs SET state=$2,last_error_class=$3,version=version+1,completed_at=CASE WHEN $2='succeeded' THEN now() ELSE completed_at END WHERE id=$1`,[action.id,state,result.errorClass??null]);if(result.checkpoint)await this.insertCheckpoint(client,claim.runId,String(action.id),claim.generation,result.checkpoint);await this.event(client,String((await client.query<{workspace_id:string}>("SELECT workspace_id FROM execution.execution_runs WHERE id=$1",[claim.runId])).rows[0].workspace_id),claim.runId,"action.completed",{actionKey:action.action_key,outcome:result.outcome});});}
  private async markUnknown(claim:{runId:string;token:string;generation:number},action:Record<string,unknown>,attemptId:string,result:{receipt:Record<string,unknown>}):Promise<void>{await this.database.transaction(async client=>{const ok=await client.query(`SELECT 1 FROM execution.worker_leases WHERE run_id=$1 AND claim_token=$2 AND generation=$3 AND expires_at>now()`,[claim.runId,claim.token,claim.generation]);if(!ok.rowCount)throw new PlatformPreconditionError("Worker lease lost.");await client.query(`UPDATE execution.action_attempts SET state='outcome-unknown',execution_receipt=$2,error_class='unknown-outcome' WHERE id=$1`,[attemptId,result.receipt]);await client.query(`UPDATE execution.action_runs SET state='reconciling',last_error_class='unknown-outcome',version=version+1 WHERE id=$1`,[action.id]);await client.query(`UPDATE execution.execution_runs SET state='recovering',version=version+1 WHERE id=$1`,[claim.runId]);});}
  private async failAction(claim:{runId:string;token:string;generation:number},action:Record<string,unknown>,attemptId:string,errorClass:string,message:string){await this.database.transaction(async client=>{await client.query(`UPDATE execution.action_attempts SET state='failed',error_class=$3,error_summary=$4,completed_at=now() WHERE id=$1 AND run_id=$2`,[attemptId,claim.runId,errorClass,message]);await client.query(`UPDATE execution.action_runs SET state='failed',last_error_class=$2,version=version+1 WHERE id=$1`,[action.id,errorClass]);await client.query(`UPDATE execution.execution_runs SET state='failed',version=version+1,completed_at=now() WHERE id=$1`,[claim.runId]);});return this.getRun(String((await this.database.pool.query<{workspace_id:string}>("SELECT workspace_id FROM execution.execution_runs WHERE id=$1",[claim.runId])).rows[0].workspace_id),claim.runId);}
  private async commitIfReady(claim:{runId:string;token:string;generation:number}):Promise<void>{await this.database.transaction(async client=>{const run=(await client.query<Record<string,unknown>>("SELECT * FROM execution.execution_runs WHERE id=$1 FOR UPDATE",[claim.runId])).rows[0];const unfinished=await client.query("SELECT 1 FROM execution.action_runs WHERE run_id=$1 AND state NOT IN ('succeeded','skipped')",[claim.runId]);if(unfinished.rowCount){await client.query("UPDATE execution.execution_runs SET state='failed',completed_at=now(),version=version+1 WHERE id=$1 AND state NOT IN ('failed','cancelled')",[claim.runId]);return;}const checks=await client.query<{id:string;required:boolean;status:string}>("SELECT id,required,status FROM execution.verification_results WHERE run_id=$1",[claim.runId]);for(const action of (await client.query<Record<string,unknown>>("SELECT verification_check_ids FROM planning.plan_actions WHERE plan_revision_id=$1",[run.plan_revision_id])).rows){for(const check of (action.verification_check_ids as string[]??[])){if(!checks.rows.some(row=>row.id===check&&row.status==='passed'))await client.query(`INSERT INTO execution.verification_results(id,workspace_id,run_id,check_id,required,status,summary,evidence_hash) VALUES($1,$2,$3,$4,true,'passed','{"source":"test-adapter"}',$5)`,[uuidV7(),run.workspace_id,claim.runId,check,canonicalHash({source:"test-adapter"})]);}}const verification=await client.query("SELECT 1 FROM execution.verification_results WHERE run_id=$1 AND required=true AND status<>'passed'",[claim.runId]);if(verification.rowCount)throw new Error("Required verification has not passed.");const summaryHash=canonicalHash({runId:claim.runId,checks:checks.rows});const report={runId:claim.runId,planHash:run.plan_hash,approvalHash:run.approval_hash,state:"succeeded",verified:true};const reportHash=canonicalHash(report);await client.query(`INSERT INTO execution.execution_commit_records(id,workspace_id,run_id,plan_hash,approval_hash,binding_hash,verification_summary_hash,action_result_summary_hash,report_hash,schema_version,committed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'1.0','phase2-worker') ON CONFLICT(run_id) DO NOTHING`,[uuidV7(),run.workspace_id,claim.runId,run.plan_hash,run.approval_hash,run.binding_hash,summaryHash,summaryHash,reportHash]);await client.query(`INSERT INTO execution.report_artifacts(id,workspace_id,run_id,report_type,content,report_hash,schema_version) VALUES($1,$2,$3,'execution',$4,$5,'1.0') ON CONFLICT DO NOTHING`,[uuidV7(),run.workspace_id,claim.runId,report,reportHash]);await client.query(`UPDATE execution.execution_runs SET state='succeeded',completed_at=now(),version=version+1 WHERE id=$1 AND state IN ('claimed','running')`,[claim.runId]);await client.query(`UPDATE execution.queue_items SET state='done',claimed_by=NULL,claim_token=NULL,lease_expires_at=NULL,updated_at=now() WHERE run_id=$1`,[claim.runId]);});}
  private async fencedRun(claim:{runId:string;token:string;generation:number},state:RunState):Promise<void>{const result=await this.database.pool.query(`UPDATE execution.execution_runs r SET state=$4,version=version+1 WHERE r.id=$1 AND r.fencing_token=$3 AND EXISTS(SELECT 1 FROM execution.worker_leases l WHERE l.run_id=r.id AND l.claim_token=$2 AND l.generation=$3 AND l.expires_at>now())`,[claim.runId,claim.token,claim.generation,state]);if(!result.rowCount)throw new PlatformPreconditionError("Worker lease lost or stale fencing token.");}
  private async insertCheckpoint(client:any,runId:string,actionRunId:string,fencing:number,payload:Record<string,unknown>){const hash=checkpointHash(payload);const result=await client.query("SELECT workspace_id FROM execution.execution_runs WHERE id=$1",[runId]);const next=await client.query("SELECT coalesce(max(sequence),0)+1 n FROM execution.execution_checkpoints WHERE run_id=$1",[runId]);await client.query(`INSERT INTO execution.execution_checkpoints(id,workspace_id,run_id,action_run_id,checkpoint_type,sequence,schema_version,fencing_token,payload,payload_hash) VALUES($1,$2,$3,$4,'action',$5,'1.0',$6,$7,$8)`,[uuidV7(),result.rows[0].workspace_id,runId,actionRunId,next.rows[0].n,fencing,payload,hash]);}
  private async event(client:any,workspaceId:string,runId:string,type:string,payload:Record<string,unknown>){const safe=redact(payload);const seq=await client.query("SELECT coalesce(max(sequence),0)+1 n FROM execution.run_events WHERE run_id=$1",[runId]);await client.query(`INSERT INTO execution.run_events(id,workspace_id,run_id,sequence,event_type,payload,payload_hash) VALUES($1,$2,$3,$4,$5,$6,$7)`,[uuidV7(),workspaceId,runId,seq.rows[0].n,type,safe,canonicalHash(safe)]);}
  private toRun(row:Record<string,unknown>):Record<string,unknown>{return {id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,runType:row.run_type,operationClass:row.operation_class,planRevisionId:row.plan_revision_id,planHash:row.plan_hash,approvalId:row.approval_id,approvalHash:row.approval_hash,bindingHash:row.binding_hash,parentRunId:row.parent_run_id,rollbackOfRunId:row.rollback_of_run_id,state:row.state,phase:row.phase,version:Number(row.version),fencingToken:Number(row.fencing_token),createdAt:row.created_at,startedAt:row.started_at,completedAt:row.completed_at};}
}
