import test, { after, before, describe } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs/promises";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import Fastify from "fastify";
import { PlatformDatabase } from "../../platform/postgres.js";
import { FoundationService } from "../../platform/service.js";
import { canonicalHash, uuidV7 } from "../../platform/foundation.js";
import { PlanningService } from "../../planning/service.js";
import { assertValidDag, compilePlan, type CompilerInput } from "../../planning/compiler.js";
import { assertPlanningSafe, evaluateReadiness, planHash, type BlueprintContent } from "../../planning/model.js";
import { dispatchOnce } from "../../platform/dispatcher.js";
import { registerPlanningRoutes } from "../../planning/routes.js";
import { registerRoutes } from "../../routes.js";
import { proposeLegacyServiceStackImport } from "../../planning/legacy-import.js";
import { _resetStoreForTests, updateRuntimeDatabase } from "../../runtime-store.js";
import { _resetSqliteDbForTests } from "../../db-sqlite.js";

let tempRoot=""; let dataDir=""; let port=0; let database:PlatformDatabase; let app=Fastify({logger:false}); let token="";

describe("Phase 1 core domain and planning", { concurrency: false }, () => {
before(async()=>{
  tempRoot=await fs.mkdtemp(path.join(os.tmpdir(),"envforge-phase1-test-")); dataDir=path.join(tempRoot,"pg"); port=await freePort();
  command("initdb",["-D",dataDir,"-A","trust","-U","postgres","--encoding=UTF8","--no-locale"]); command("pg_ctl",["-D",dataDir,"-o",`-p ${port} -h 127.0.0.1`,"-w","start"],true);
  const created = command("createdb",["-h","127.0.0.1","-p",String(port),"-U","postgres","envforge_phase1_test"]); if(created.status!==0) throw new Error("Disposable Phase 1 database creation failed.");
  const databases = command("psql",["-h","127.0.0.1","-p",String(port),"-U","postgres","-d","postgres","-tAc","select 1 from pg_database where datname='envforge_phase1_test'"]); if(!databases.stdout.includes("1")) throw new Error("Disposable Phase 1 database was not created.");
  database=new PlatformDatabase(`postgres://postgres@127.0.0.1:${port}/envforge_phase1_test`); await database.migrate();
  process.env.FOOL_RUNTIME_DB=path.join(tempRoot,"runtime.json"); process.env.FOOL_DATA_DIR=path.join(tempRoot,"legacy-data"); process.env.NODE_ENV="test"; process.env.ENVFORGE_MASTER_KEY ||= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
  await fs.writeFile(process.env.FOOL_RUNTIME_DB,JSON.stringify({schemaVersion:"0.3.0",users:[],sessions:[],connections:[],userProfiles:[],tasks:[],playbooks:[]})); _resetStoreForTests();
  token=`phase1-${uuidV7()}`; await updateRuntimeDatabase((store)=>{store.users.push({id:"phase1-admin",name:"Phase 1 Admin",username:"phase1-admin",email:"phase1@example.test",role:"admin",passwordHash:"x",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()} as never);store.sessions.push({token,userId:"phase1-admin",createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString()} as never);});
  app=Fastify({logger:false}); await registerRoutes(app); await registerPlanningRoutes(app,database);
});
after(async()=>{await app.close();await database.close();await _resetSqliteDbForTests();if(dataDir)command("pg_ctl",["-D",dataDir,"-m","fast","-w","stop"],true,true);if(tempRoot)await fs.rm(tempRoot,{recursive:true,force:true});});

test("Phase 1 production migration is scoped, replayable, and excludes Phase 4/2 tables",async()=>{
  const migrations=await database.migrate(); assert.equal(migrations.length,3); assert.equal((await database.migrate()).length,3);
  const tables=await database.pool.query<{name:string|null}>("SELECT to_regclass('workload.blueprint_revisions') name UNION ALL SELECT to_regclass('planning.plan_revisions') UNION ALL SELECT to_regclass('discovery.workload_candidates') UNION ALL SELECT to_regclass('planning.execution_runs')");
  assert.ok(tables.rows[0].name);assert.ok(tables.rows[1].name);assert.equal(tables.rows[2].name,null);assert.equal(tables.rows[3].name,null);
});

test("Project type and mode-specific transitions are enforced",async()=>{
  const foundation=new FoundationService(database);const workspaceId=await foundation.ensurePersonalWorkspace("project-user","Project");const planning=new PlanningService(database);
  const project=(await foundation.createProject(ctx(workspaceId,"project-user","project"),{type:"build",name:"Build lifecycle"})).project;
  const defining=await planning.transitionProject(ctx(workspaceId,"project-user","transition-1"),project.id,0,"defining") as {status:string;version:number};assert.equal(defining.status,"defining");
  await assert.rejects(()=>planning.transitionProject(ctx(workspaceId,"project-user","transition-bad"),project.id,defining.version,"completed"),/Illegal build project transition/);
  await assert.rejects(()=>database.pool.query("UPDATE core.projects SET project_type='migration' WHERE id=$1",[project.id]),/project_type is immutable/);
});

test("Project lineage is workspace-scoped and supports multiple Restore derivations",async()=>{
  const foundation=new FoundationService(database);const planning=new PlanningService(database);const workspaceId=await foundation.ensurePersonalWorkspace("lineage-user","Lineage");
  const capture=(await foundation.createProject(ctx(workspaceId,"lineage-user","capture"),{type:"capture",name:"Capture lineage"})).project;
  const restore1=(await foundation.createProject(ctx(workspaceId,"lineage-user","restore1"),{type:"restore",name:"Restore one"})).project;const restore2=(await foundation.createProject(ctx(workspaceId,"lineage-user","restore2"),{type:"restore",name:"Restore two"})).project;
  await planning.createProjectLink(ctx(workspaceId,"lineage-user","link1"),capture.id,restore1.id,"restores-archive");await planning.createProjectLink(ctx(workspaceId,"lineage-user","link2"),capture.id,restore2.id,"restores-archive");
  const other=await foundation.ensurePersonalWorkspace("lineage-other","Other");const foreign=(await foundation.createProject(ctx(other,"lineage-other","foreign"),{type:"restore",name:"Foreign restore"})).project;
  await assert.rejects(()=>planning.createProjectLink(ctx(workspaceId,"lineage-user","bad-link"),capture.id,foreign.id,"restores-archive"));
});

test("Blueprint contract is complete, secret-safe, confirmed immutable, and revisions are concurrency-safe",async()=>{
  const fixture=await seeded("blueprint");const planning=new PlanningService(database);const content=blueprint();
  assert.throws(()=>assertPlanningSafe({secretValue:"envforge-secret-canary"}),/Secret/);assert.equal(evaluateReadiness(content,"build").status,"planner-ready");
  const draft=await planning.createBlueprintDraft(ctx(fixture.workspaceId,"author","draft"),fixture.workload.id,content);const confirmed=await planning.confirmBlueprint(ctx(fixture.workspaceId,"author","confirm"),draft.id,0);assert.equal(confirmed.status,"confirmed");
  await assert.rejects(()=>database.pool.query("UPDATE workload.blueprint_revisions SET content='{}'::jsonb WHERE id=$1",[confirmed.id]),/immutable/);
  const [successorA,successorB]=await Promise.all([planning.createBlueprintDraft(ctx(fixture.workspaceId,"author","successor-a"),fixture.workload.id,{...content,knownLimitations:["a"]}),planning.createBlueprintDraft(ctx(fixture.workspaceId,"author","successor-b"),fixture.workload.id,{...content,knownLimitations:["b"]})]);
  assert.notEqual(successorA.revision,successorB.revision);
});

test("EphemeralStatePolicy blocks unresolved critical state",()=>{const content=blueprint();content.ephemeralState.activeWriters="blocked";const result=evaluateReadiness(content,"migration");assert.equal(result.status,"blocked");assert.ok(result.blockers.includes("ephemeral-state:activeWriters"));});

test("Workload placement and expiring MigrationEstimate preserve authority-neutral identity",async()=>{const fixture=await seeded("placement");const planning=new PlanningService(database);const endpoint=await new FoundationService(database).createEndpoint(ctx(fixture.workspaceId,"author","placement-endpoint"),{kind:"linux-host",displayName:"Target",hostIdentity:{hostname:"target.example.test"}});const placement=await planning.createPlacement(ctx(fixture.workspaceId,"author","placement-create"),{workloadId:fixture.workload.id,projectId:fixture.project.id,endpointId:endpoint.id,placementType:"target",authorityState:"none"}) as {authorityState:string};assert.equal(placement.authorityState,"none");const calculatedAt=new Date();const estimate=await planning.createMigrationEstimate(ctx(fixture.workspaceId,"author","estimate"),{projectId:fixture.project.id,estimate:{sourceBytes:1024,writeRateBytesPerSecond:10,downtimeRangeSeconds:[10,30],targetDiskHeadroomBytes:4096,missingEvidence:[]},confidence:"medium",calculatedAt:calculatedAt.toISOString(),expiresAt:new Date(calculatedAt.getTime()+3600000).toISOString()}) as {version:number};assert.equal(estimate.version,1);await assert.rejects(()=>planning.createPlacement(ctx(fixture.workspaceId,"author","placement-invalid"),{workloadId:fixture.workload.id,placementType:"archived",authorityState:"historical"}),/endpoint or archive/);});

test("Legacy ServiceStack import is review-required, deterministic, and never copies secret content or approval",()=>{const input={id:"legacy-stack",name:"Legacy web",service:{name:"node",unit:"app.service"},packages:[{name:"nodejs"}],configs:[{path:"/srv/app/.env",containsSecret:true}],ports:[8080]};const first=proposeLegacyServiceStackImport(input);const second=proposeLegacyServiceStackImport(input);assert.deepEqual(second,first);assert.equal(first.state,"review-required");assert.ok(first.unresolved.includes("secret-provider-binding"));assert.doesNotMatch(JSON.stringify(first),/password=|token=|envforge-secret-canary/i);assert.equal("approval" in first,false);});

test("DecisionSet is immutable and hard blockers cannot be risk accepted",async()=>{const fixture=await seeded("decision");const planning=new PlanningService(database);const first=await planning.createDecisionSet(ctx(fixture.workspaceId,"author","decision-1"),fixture.project.id,{conflicts:{port:"reuse"}});const second=await planning.createDecisionSet(ctx(fixture.workspaceId,"author","decision-2"),fixture.project.id,{conflicts:{port:"rename"}});assert.equal(second.revision,first.revision+1);await assert.rejects(()=>database.pool.query("UPDATE planning.decision_set_revisions SET content='{}'::jsonb WHERE id=$1",[first.id]),/immutable/);await assert.rejects(()=>planning.createDecisionSet(ctx(fixture.workspaceId,"author","decision-hard"),fixture.project.id,{riskAcceptances:[{riskId:"hard-blocker:data-owner",reason:"ignore"}]}),/Hard blockers/);});

test("Compiler is deterministic for 100 repeats, input-sensitive, multi-Blueprint, and acyclic",()=>{
  const input=compilerInput();const first=compilePlan(input);assert.notEqual(first.outcome,"blocked");if(first.outcome==="blocked")return;for(let i=0;i<100;i++)assert.equal((compilePlan({...input,blueprints:[...input.blueprints].reverse()}) as {hash:string}).hash,first.hash);
  const changed=compilePlan({...input,policy:{...input.policy,hash:"1".repeat(64)}});assert.notEqual(changed.outcome,"blocked");if(changed.outcome!=="blocked")assert.notEqual(changed.hash,first.hash);
  assert.equal(first.plan.bindings.filter((binding)=>binding.type==="blueprint").length,2);assert.doesNotThrow(()=>assertValidDag(first.plan.actions,first.plan.dependencies));
  const [a,b]=first.plan.actions;assert.throws(()=>assertValidDag(first.plan.actions,[{fromActionId:a.id,toActionId:b.id,type:"must-succeed-before"},{fromActionId:b.id,toActionId:a.id,type:"must-succeed-before"}]),/cycle/);assert.equal(planHash(first.plan),first.hash);
});

test("Migration/Capture/Restore produce truthful blockers without certified capability",()=>{for(const mode of ["migration","capture","restore"] as const){const input=compilerInput();const result=compilePlan({...input,mode,capability:{...input.capability,certifiedModes:["build"]},sourceSnapshot:{id:"source",hash:"a".repeat(64)},archiveVersion:{id:"archive",hash:"b".repeat(64)}});assert.equal(result.outcome,"blocked");if(result.outcome==="blocked")assert.match(result.blockers[0],/capability-unavailable/);}});

test("ControlPlaneOperation compiles and persists one immutable Plan after duplicate delivery",async()=>{
  const fixture=await seeded("compile");const planning=new PlanningService(database);const draft=await planning.createBlueprintDraft(ctx(fixture.workspaceId,"author","compile-draft"),fixture.workload.id,blueprint());const confirmed=await planning.confirmBlueprint(ctx(fixture.workspaceId,"author","compile-confirm"),draft.id,0);const decision=await planning.createDecisionSet(ctx(fixture.workspaceId,"author","compile-decision"),fixture.project.id,{});
  const operationId=await planning.requestCompilation(ctx(fixture.workspaceId,"author","compile-request"),{projectId:fixture.project.id,mode:"build",blueprintRevisionIds:[confirmed.id],decisionSetRevisionId:decision.id,targetSnapshot:{id:"target-snapshot",hash:"c".repeat(64)},capability:{id:"builtin",hash:"d".repeat(64),version:"1",certifiedModes:["build"]},policy:{id:"policy",hash:"e".repeat(64),version:"1"}});
  assert.equal((await planning.getCompilation(fixture.workspaceId,operationId)).state,"queued");assert.equal(await dispatchOnce(database,"operation","phase1-compiler"),1);const done=await planning.getCompilation(fixture.workspaceId,operationId);if(done.state!=="succeeded"){const failure=await database.pool.query("SELECT state,last_error FROM audit.outbox_messages WHERE topic='planning.compilation.requested' AND payload->>'operationId'=$1",[operationId]);assert.fail(`compilation remained ${done.state}: ${JSON.stringify(failure.rows)}`);}assert.equal(done.outcome,"compiled");assert.ok(done.resultPlanRevisionId);
  const plan=await planning.getPlan(fixture.workspaceId,done.resultPlanRevisionId!);assert.equal(plan.status,"compiled");assert.equal(plan.canonicalContent.actions.length,3);assert.equal(await dispatchOnce(database,"operation","phase1-compiler-replay"),0);
  await assert.rejects(()=>database.pool.query("UPDATE planning.plan_revisions SET canonical_content='{}'::jsonb WHERE id=$1",[plan.id]),/immutable/);
  const runTable=await database.pool.query("SELECT to_regclass('planning.execution_runs') value");assert.equal(runTable.rows[0].value,null);
});

test("Blocked compilation succeeds as a diagnostic operation but creates no Plan",async()=>{
  const fixture=await seeded("blocked");const planning=new PlanningService(database);const content=blueprint();content.ephemeralState.activeWriters="blocked";const draft=await planning.createBlueprintDraft(ctx(fixture.workspaceId,"author","blocked-draft"),fixture.workload.id,content);const confirmed=await planning.confirmBlueprint(ctx(fixture.workspaceId,"author","blocked-confirm"),draft.id,0);const decision=await planning.createDecisionSet(ctx(fixture.workspaceId,"author","blocked-decision"),fixture.project.id,{});const operationId=await planning.requestCompilation(ctx(fixture.workspaceId,"author","blocked-request"),{projectId:fixture.project.id,mode:"build",blueprintRevisionIds:[confirmed.id],decisionSetRevisionId:decision.id,targetSnapshot:{id:"target",hash:"1".repeat(64)},capability:{id:"builtin",hash:"2".repeat(64),version:"1",certifiedModes:["build"]},policy:{id:"policy",hash:"3".repeat(64),version:"1"}});await dispatchOnce(database,"operation","blocked-compiler");const result=await planning.getCompilation(fixture.workspaceId,operationId);assert.equal(result.outcome,"blocked");assert.equal(result.resultPlanRevisionId,undefined);assert.equal((await planning.listPlans(fixture.workspaceId,fixture.project.id)).length,0);
});

test("Approval binds exact hash, separates duties, detects drift, and never creates a Run",async()=>{
  const fixture=await compiled("approval");const planning=new PlanningService(database);const pending=await planning.submitForApproval(ctx(fixture.workspaceId,"author","submit"),fixture.plan.id,0);assert.equal(pending.approvedPlanHash,fixture.plan.planHash);await assert.rejects(()=>planning.decideApproval(ctx(fixture.workspaceId,"author","self-approve"),pending.id,0,"approved","self"),/different approver/);const approved=await planning.decideApproval(ctx(fixture.workspaceId,"approver","approve"),pending.id,0,"approved","reviewed");assert.equal(approved.status,"approved");const current=fixture.plan.canonicalContent.bindings.map((binding)=>({type:binding.type,key:binding.key,hash:binding.hash}));assert.equal((await planning.evaluateMaterialDrift(fixture.workspaceId,fixture.plan.id,current)).materialDrift,false);current[0]={...current[0],hash:"9".repeat(64)};assert.equal((await planning.evaluateMaterialDrift(fixture.workspaceId,fixture.plan.id,current)).recompileRequired,true);assert.equal((await database.pool.query("SELECT to_regclass('planning.execution_runs') value")).rows[0].value,null);
});

test("Planning API is workspace-scoped and Run creation remains locked",async()=>{const foundation=new FoundationService(database);const workspaceId=await foundation.ensurePersonalWorkspace("phase1-admin","Admin");const project=(await foundation.createProject(ctx(workspaceId,"phase1-admin","api-project"),{type:"build",name:`API ${uuidV7()}`})).project;const headers={authorization:`Bearer ${token}`,"x-workspace-id":workspaceId,"idempotency-key":"api-workload"};const created=await app.inject({method:"POST",url:`/api/v1/projects/${project.id}/workloads`,headers,payload:{name:`Web ${uuidV7()}`,kind:"web-app"}});assert.equal(created.statusCode,201,created.body);const locked=await app.inject({method:"POST",url:`/api/v1/plans/${uuidV7()}/runs`,headers});assert.equal(locked.statusCode,404);assert.equal((locked.json() as {code:string}).code,"RUN_NOT_AVAILABLE");const other=await foundation.ensurePersonalWorkspace("other-api","Other");const denied=await app.inject({method:"GET",url:`/api/v1/projects/${project.id}/workloads`,headers:{authorization:`Bearer ${token}`,"x-workspace-id":other}});assert.equal(denied.statusCode,404,denied.body);});
});

async function seeded(label:string){const foundation=new FoundationService(database);const workspaceId=await foundation.ensurePersonalWorkspace(`${label}-${uuidV7()}`,label);const project=(await foundation.createProject(ctx(workspaceId,"author",`${label}-project`),{type:"build",name:`${label}-${uuidV7()}`})).project;const planning=new PlanningService(database);const workload=await planning.createWorkload(ctx(workspaceId,"author",`${label}-workload`),project.id,{name:`${label}-workload-${uuidV7()}`,kind:"web-app"});return{workspaceId,project,workload};}
async function compiled(label:string){const fixture=await seeded(label);const planning=new PlanningService(database);const draft=await planning.createBlueprintDraft(ctx(fixture.workspaceId,"author",`${label}-draft`),fixture.workload.id,blueprint());const confirmed=await planning.confirmBlueprint(ctx(fixture.workspaceId,"author",`${label}-confirm`),draft.id,0);const decision=await planning.createDecisionSet(ctx(fixture.workspaceId,"author",`${label}-decision`),fixture.project.id,{});const operationId=await planning.requestCompilation(ctx(fixture.workspaceId,"author",`${label}-compile`),{projectId:fixture.project.id,mode:"build",blueprintRevisionIds:[confirmed.id],decisionSetRevisionId:decision.id,targetSnapshot:{id:"target",hash:"a".repeat(64)},capability:{id:"builtin",hash:"b".repeat(64),version:"1",certifiedModes:["build"]},policy:{id:"policy",hash:"c".repeat(64),version:"1"}});await dispatchOnce(database,"operation",`${label}-worker`);const operation=await planning.getCompilation(fixture.workspaceId,operationId);return{...fixture,plan:await planning.getPlan(fixture.workspaceId,operation.resultPlanRevisionId!)};}
function compilerInput():CompilerInput{return{projectId:"project",mode:"build",blueprints:[{id:"blueprint-b",workloadId:"workload-b",hash:"b".repeat(64),content:blueprint("B")},{id:"blueprint-a",workloadId:"workload-a",hash:"a".repeat(64),content:blueprint("A")}],decision:{id:"decision",hash:"c".repeat(64),content:{}},targetSnapshot:{id:"target",hash:"d".repeat(64)},capability:{id:"builtin",hash:"e".repeat(64),version:"1",certifiedModes:["build"]},policy:{id:"policy",hash:"f".repeat(64),version:"1"}};}
function blueprint(name="App"):BlueprintContent{return{identity:{name,kind:"web-app",provenance:{source:"fixture"},scope:{}},components:[{key:"app",kind:"service"}],runtime:{executionModel:"systemd",entrypoint:"artifact-entrypoint-ref",workingDirectory:"/srv/app",runUser:"app",runGroup:"app",environmentRefs:[],environmentFileRefs:["secret-requirement:app-env"],enabled:true,desiredState:"active",restartPolicy:"on-failure",restartDelaySeconds:5,after:["network-online.target"],before:[],wants:["network-online.target"],requires:[],startupTimeoutSeconds:60,shutdownTimeoutSeconds:30,resourceLimits:{},securityContext:{noNewPrivileges:true},socketActivation:false,timerActivation:false,healthCheck:{kind:"http",path:"/health"},allowedWritePaths:["/srv/app/uploads"],stateDirectories:["app"],runtimeDirectories:["app"]},deployment:{sourceType:"git",reference:"https://example.test/repo.git",exactVersion:"0123456789abcdef",checksum:"a".repeat(64),lockfile:"package-lock.json",provenance:{repository:"example"},fallbackStrategy:"blocked"},config:[{key:"app-config",classification:"portable",sanitizedArtifactRef:"artifact:config",validationCommandRef:"capability:validate-config",owner:"app",mode:"0640"}],datasets:[],secretRequirements:[{id:"app-env",purpose:"application environment",providerBindingRef:"provider-ref:app-env",required:true}],endpoints:[{kind:"http",port:8080}],systemIdentities:[{user:"app",group:"app"}],scheduledTasks:[],dependencies:[],externalDependencies:[],ephemeralState:{httpRequests:"drain",databaseTransactions:"quiesce",fileLocks:"restart",activeWriters:"quiesce",inMemorySessions:"discard-with-warning",activeJobs:"requeue",leaderElection:"restart",scheduledExecutions:"requeue",unpersistedMessages:"requeue"},compatibility:{architectures:["x64"]},verification:[{kind:"http",path:"/health"}],operationalRequirements:{},migrationRequirements:{},captureRequirements:{},knownLimitations:[]};}
function ctx(workspaceId:string,actorId:string,key:string){return{actorId,workspaceId,requestId:uuidV7(),correlationId:uuidV7(),idempotencyKey:key};}
async function freePort(){return new Promise<number>((resolve,reject)=>{const server=net.createServer();server.once("error",reject);server.listen(0,"127.0.0.1",()=>{const address=server.address();const value=typeof address==="object"&&address?address.port:0;server.close((error)=>error?reject(error):resolve(value));});});}
function command(name:string,args:string[],quiet=false,allowFailure=false){const executable={initdb:"E:/PostgreSQL/17/bin/initdb.exe",pg_ctl:"E:/PostgreSQL/17/bin/pg_ctl.exe",createdb:"E:/PostgreSQL/17/bin/createdb.exe",psql:"E:/PostgreSQL/17/bin/psql.exe"}[name as "initdb"|"pg_ctl"|"createdb"|"psql"]??name;const result=spawnSync(executable,args,{encoding:"utf8",windowsHide:true,stdio:quiet?"ignore":"pipe",timeout:60000});if(!quiet&&result.stdout)process.stdout.write(result.stdout);if(result.status!==0&&!allowFailure)throw new Error(`${name} ${args.join(" ")} failed (${result.status}): ${result.stderr}`);return result;}
